config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :posts
  resources :smsmsgs
  resources :users
  root to: 'visitors#index'
  post 'post/twilio_create' =>'post#twilio_create'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
=======
  root to: 'visitors#index'
  devise_for :users
  resources :users
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/smsmsg.rb
class Smsmsg < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
<<<<<<< HEAD

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

=======
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
<<<<<<< HEAD

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

=======
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00
end

app/controllers/concerns/Webhookable.rb
module Webhookable
extend ActiveSupport::Concern

  def set_header
  	response.headers["Content-Type"] = "text/xml"
  end

  def render_twiml(response)
  	render text: response.text
  end

end

app/controllers/posts_controller.rb
require 'twilio-ruby'

class PostsController < ApplicationController
  include Webhookable

  skip_before_filter :verify_authenticity_token
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

   def twilio_create
    @post = Post.new(:body => params["Body"], :from_phone_no => params["From"])
    @post.save

    twiml = Twilio::TwiML::Response.new do |r|
      r.Message 'Your Text has been received '
    end  

    twiml.text
   end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :city, :country, :from_phone_no, :city, :state)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/smsmsgs_controller.rb
class SmsmsgsController < ApplicationController
  before_action :set_smsmsg, only: [:show, :edit, :update, :destroy]
  require 'twilio-ruby'

  # GET /smsmsgs
  # GET /smsmsgs.json
  def index
    @smsmsgs = Smsmsg.all
  end

  # GET /smsmsgs/1
  # GET /smsmsgs/1.json
  def show
  end

  # GET /smsmsgs/new
  def new
    @smsmsg = Smsmsg.new
  end

  # GET /smsmsgs/1/edit
  def edit
  end

  # POST /smsmsgs
  # POST /smsmsgs.json
  def create
    @smsmsg = Smsmsg.new(smsmsg_params)

    respond_to do |format|
      if @smsmsg.save
        format.html { redirect_to @smsmsg, notice: 'Smsmsg was successfully created.' }
        format.json { render :show, status: :created, location: @smsmsg }
      else
        format.html { render :new }
        format.json { render json: @smsmsg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smsmsgs/1
  # PATCH/PUT /smsmsgs/1.json
  def update
    respond_to do |format|
      if @smsmsg.update(smsmsg_params)
        format.html { redirect_to @smsmsg, notice: 'Smsmsg was successfully updated.' }
        format.json { render :show, status: :ok, location: @smsmsg }
      else
        format.html { render :edit }
        format.json { render json: @smsmsg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smsmsgs/1
  # DELETE /smsmsgs/1.json
  def destroy
    @smsmsg.destroy
    respond_to do |format|
      format.html { redirect_to smsmsgs_url, notice: 'Smsmsg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def send_message(phone_number, alert_message, image_url)

      @twilio_number = ENV['TWILIO_NUMBER']
      @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    # Use callbacks to share common setup or constraints between actions.
    def set_smsmsg
      @smsmsg = Smsmsg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smsmsg_params
      params.require(:smsmsg).permit(:phone_no_to, :phone_no_from, :body)
    end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
<<<<<<< HEAD
  before_action :authenticate_user!
  before_action :correct_user?, :except => [:index]
=======
  before_filter :authenticate_user!
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
<<<<<<< HEAD
=======
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/smsmsgs_helper.rb
module SmsmsgsHelper
end

app/views/layouts/_messages.html.erb
<<<<<<< HEAD
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
=======
<%# Rails flash messages styled for Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<<<<<<< HEAD
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>
=======
<%# navigation styled for Bootstrap 2.3 %>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <div class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <ul class="nav">
              <li><%= link_to 'Home', root_path %><li>
              <%= render 'layouts/navigation_links' %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<<<<<<< HEAD
<li><%= link_to 'About', page_path('about') %></li>
=======
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<<<<<<< HEAD
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
=======
    <title><%= content_for?(:title) ? yield(:title) : "Smsapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Smsapp" %>">
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
<<<<<<< HEAD
    <header>
      <%= render 'layouts/navigation' unless current_page?(root_path) %>
    </header>
      <%= render 'layouts/messages' %>
      <%= yield %>
=======
    <%# application layout styled for Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :from_phone_no %>
    <%= f.input :to_phone_no %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>From phone no</th>
      <th>To phone no</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.from_phone_no %></td>
        <td><%= post.to_phone_no %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From phone no:</strong>
  <%= @post.from_phone_no %>
</p>

<p>
  <strong>To phone no:</strong>
  <%= @post.to_phone_no %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/smsmsgs/_form.html.erb
<%= simple_form_for(@smsmsg) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :phone_no_to %>
    <%= f.input :phone_no_from %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/smsmsgs/edit.html.erb
<h1>Editing Smsmsg</h1>

<%= render 'form' %>

<%= link_to 'Show', @smsmsg %> |
<%= link_to 'Back', smsmsgs_path %>

app/views/smsmsgs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Smsmsgs</h1>

<table>
  <thead>
    <tr>
      <th>Phone no to</th>
      <th>Phone no from</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @smsmsgs.each do |smsmsg| %>
      <tr>
        <td><%= smsmsg.phone_no_to %></td>
        <td><%= smsmsg.phone_no_from %></td>
        <td><%= smsmsg.body %></td>
        <td><%= link_to 'Show', smsmsg %></td>
        <td><%= link_to 'Edit', edit_smsmsg_path(smsmsg) %></td>
        <td><%= link_to 'Destroy', smsmsg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Smsmsg', new_smsmsg_path %>

app/views/smsmsgs/new.html.erb
<h1>New Smsmsg</h1>

<%= render 'form' %>

<%= link_to 'Back', smsmsgs_path %>

app/views/smsmsgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone no to:</strong>
  <%= @smsmsg.phone_no_to %>
</p>

<p>
  <strong>Phone no from:</strong>
  <%= @smsmsg.phone_no_from %>
</p>

<p>
  <strong>Body:</strong>
  <%= @smsmsg.body %>
</p>

<%= link_to 'Edit', edit_smsmsg_path(@smsmsg) %> |
<%= link_to 'Back', smsmsgs_path %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<<<<<<< HEAD
=======
<td><%= link_to user.email, user %></td>
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<<<<<<< HEAD
=======
<p>Email: <%= @user.email if @user.email %></p>
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00

app/views/visitors/index.html.erb
<<<<<<< HEAD
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#about">About</a>
                </li>
                <li>
                    <a href="#services">Services</a>
                </li>
                <li>
                    <a href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Full Width Image Header -->
<header class="header-image">
    <div class="headline">
        <div class="container">
            <h1>One Page Wonder</h1>
            <h2>Will Knock Your Socks Off</h2>
        </div>
    </div>
</header>

<!-- Page Content -->
<div class="container">

    <hr class="featurette-divider">

    <!-- First Featurette -->
    <div class="featurette" id="about">
        <img class="featurette-image img-circle img-responsive pull-right" src="http://placehold.it/500x500">
        <h2 class="featurette-heading">This First Heading
            <span class="text-muted">Will Catch Your Eye</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Second Featurette -->
    <div class="featurette" id="services">
        <img class="featurette-image img-circle img-responsive pull-left" src="http://placehold.it/500x500">
        <h2 class="featurette-heading">The Second Heading
            <span class="text-muted">Is Pretty Cool Too.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Third Featurette -->
    <div class="featurette" id="contact">
        <img class="featurette-image img-circle img-responsive pull-right" src="http://placehold.it/500x500">
        <h2 class="featurette-heading">The Third Heading
            <span class="text-muted">Will Seal the Deal.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->
=======
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>
>>>>>>> 9f35aceee3e5cb45a3e7d537f52f16af035aff00